### ISSUE TITLE
"Compute.hx: Type required for extern classes and interfaces" errors

### ISSUE THREAD

**Issue by thoughton** [Kha-Samples/ComputeShader#1]
I get the following errors when trying to run via OSX Kode Studio 16.8.0:

```
.../ComputeShader/Kha/Sources/kha/compute/Compute.hx:6: characters 15-75 : Type required for extern classes and interfaces
.../ComputeShader/Kha/Sources/kha/compute/Compute.hx:7: characters 15-70 : Type required for extern classes and interfaces
.../ComputeShader/Kha/Sources/kha/compute/Compute.hx:8: characters 15-50 : Type required for extern classes and interfaces
.../ComputeShader/Kha/Sources/kha/compute/Compute.hx:9: characters 15-56 : Type required for extern classes and interfaces
```

(Since getting this latest Kode Studio it also seems to struggle with "intellisense" suggestions, so maybe there's something deeper going wrong...)

Also, I do tend to use the Haxelib Kha, but I presumed that since this repo has Kha as a submodule it would automatically use that.  Perhaps I was wrong about this?

**Edit:** I also get the same errors if I try to run using `node Kha/make html5` from the command line.

Thanks!

**Comment by lewislepton** [comment]
same as well for myself with building computeshader

**Comment by RobDangerous** [comment]
Doesn't work in html5 (and consequently Kode Studio as long as the debugger is html5-based) because browsers do not support compute shaders (also looking at https://en.wikipedia.org/wiki/WebCL things don't look good currently).
About your intellisense problem, please try to download Kode Studio again, there was a broken build for OSX.

**Comment by thoughton** [comment]
Ahha, that would explain it, thanks! :)

Unfortunately I'm having a problem when building for OSX too, but I've posted that as a new Issue.

(Regarding the Intellisense, that's much better now, thanks!)
