### ISSUE TITLE
Can't run this sample

### ISSUE THREAD

**Issue by ogxd** [Kha-Samples/ComputeShader#6]
Hi.

I am unable to run this sample. When compiling, it simply says that files are copied and stops here. I tried recreating the sample from scratch and now I get an exception on `using kha.compute.Access` (it says it doesn't exists).

Am I missing something ?

**Comment by RobDangerous** [comment]
kha.compute.Access clearly does exist, so... yes, you are missing something, looks like the problem is on your side.

**Comment by RobDangerous** [comment]
Was it maybe because the submodule reference is relative and you ignored some git-errors? Anyway, changing that.
